version: "3.2"
services:
  frontend-vue-git-hub:
    image: node:10
    container_name: frontend-vue-git-hub
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./web:/home/node/app
    command:
      sh -c 'npm i && npm run dev'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    networks:
      - network-allblacks
networks:
  network-allblacks:
    driver: bridge
