apiVersion: v1
kind: Service
metadata:
  name: service-webapp
spec:
  type: NodePort
  selector:
    app: simples-webapp
  ports:
    -
      port: 8084
      nodePort: 30001
      targetPort: porta-webapp


#apiVersion: v1
#kind: Service
#metadata:
#  name: webgateway
#  namespace: openplatform
#spec:
#  ports:
#    - port: 8000
#      targetPort: 8000
#  selector:
#    app: opengateway